# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# 2016-12-29

f1 = 1
f2 = 2
accumulator = 0
upper_bound = 4000000

while (f1 < upper_bound):
	if f1 % 2 == 0:
		accumulator += f1

	temp = f1 + f2 
	f1 = f2
	f2 = temp

print "The sum of the even terms of the Fibonacci sequence",
print " up to %r is " % upper_bound,
print accumulator